### ISSUE TITLE
Forms/Template

### ISSUE THREAD

**Issue by mart0855** [algonquindesign-grads/2015#1]
- [x] Establish file naming conventions (ie: lastname-title.jpg)
- [x] Post google form for content on discussion page (website url, email, twitter handle, etc.)
- [x] Create "grad2015" dropbox folder on school server
- [x] PSD template for portfolio pieces (600px:400px?)

**Comment by shelleybabij** [comment]
Form created.
Thomas will open dropbox folder for us.

**Comment by thomasjbradley** [comment]
The dropbox should be accessible on the Algonquin network.
There's a folder named "Common Area", and I created a folder inside it named "-- 2015 Grad".
Everybody should have read/write access to that—let me know if it doesn't work.

**Comment by hbrittany** [comment]
Should I drop the PSD template for portfolio pieces into the "website submission" folder in dropbox? Or are we just sending it out in an announcement via canvas on Monday?

**Comment by mart0855** [comment]
It would be good to have both in case someone does not know to check the dropbox.

On Jan 15, 2015, at 11:40 AM, Brittany Hogg <notifications@github.com<mailto:notifications@github.com>> wrote:


Should I drop the PSD template for portfolio pieces into the "website submission" folder in dropbox? Or are we just sending it out in an announcement via canvas on Monday?

**Comment by hbrittany** [comment]
Ok, I have dropped it into the dropbox.
