### ISSUE TITLE
content-template.js

### ISSUE THREAD

**Issue by eprochnau** [algonquindesign-grads/2015#13]
```js
var people = [
/*
	{
		name: 'FirstName LastName',
		id: 'lastname-firstname',
		website: 'http://johnsmith.ca',
		email: 'hey@johnsmith.ca',
		skills: 'Branding, UX, Web',
		behance: false,
		dribbble: false,
		facebook: 'http://facebook.com/johnsmith'
		github: false,
		instagram: 'http://instagram.com/johnsmith',
		linkedin: false,
		pinterest: false,
		twitter: 'http://twitter.com/johnsmith',
		vimeo: false,
		works: [
			'1',
			'2',
			'3', **Use the SRC tag from the embed code that Vimeo supplies for any Vimeo submissions**
			'4'
		]
	},
*/

	{
		name: 'FirstName LastName',
		id: 'lastname-firstname',
		website: 'http://johnsmith.ca',
		email: 'hey@johnsmith.ca',
		skills: 'Branding, UX, Web',
		behance: false,
		dribbble: false,
		facebook: 'http://facebook.com/johnsmith'
		github: false,
		instagram: 'http://instagram.com/johnsmith',
		linkedin: false,
		pinterest: false,
		twitter: 'http://twitter.com/johnsmith',
		vimeo: false,
		works: [
			'1',
			'2',
			'3', **Use the SRC tag from the embed code that Vimeo supplies for any Vimeo submissions**
			'4'
		]
		
	},
};
```

**Comment by mart0855** [comment]
The site is looking really good so far. I just wanted to make a note that Emily has a duplicate in the content-template.js  line 1376.

**Comment by eprochnau** [comment]
I took a look at the content-template.js file and I think Shelley has already fixed that. She went through and corrected any minor typos or errors.

**Comment by thomasjbradley** [comment]
There's a bunch of commas missing, here between every object:
https://github.com/algonquindesign-grads/2015/blob/gh-pages/js/content-template.js#L73-L75

At the very bottom there’s a closing square bracket and semi-colon missing.

**Comment by eprochnau** [comment]
I went through and added all the commas and closing brackets. Is there anything else we're missing in this file?

**Comment by thomasjbradley** [comment]
I validated it and it looks good—only 1 small issue:
https://github.com/algonquindesign-grads/2015/blob/gh-pages/js/content-template.js#L33

There's a comma missing at the end of this line.

**Comment by eprochnau** [comment]
I fixed it. Can we close this issue now or are we going to wait until Mark has had a chance to use the file?

**Comment by coll0335** [comment]
I fixed the missing comas when i was working on it. If you guys can, take a
look at the most current one if you haven't.
Still having difficulties on getting the info to load for the light box
