### ISSUE TITLE
Refinement of Styling

### ISSUE THREAD

**Issue by mart0855** [algonquindesign-grads/2015#16]
- [x] Shrink logo in nav and link "back to top"
- [x] Make overlay buttons reflect mockup
- [x] White box container in overlay
- [x] Hook-up Google maps
- [x] Remove link styling on names

**Comment by thomasjbradley** [comment]
Are the overlay buttons just supposed to be boxes? Or are their going to be icons in them? Right now it's really confusing what they do.

**Comment by thomasjbradley** [comment]
![screen shot 2015-03-03 at 5 08 29 pm](https://cloud.githubusercontent.com/assets/105192/6473538/f7b44ecc-c1c7-11e4-80ff-211a783c4ce1.png)

**Comment by coll0335** [comment]
hooked up google maps, however, there is a conflict. I also, have set up the video on the homepage. We just need a toggle to play and pause the video on command. Also, I talked to Stephen and decided. The the logo and the Arrow on the video area will be hidden to begin with but when the user pauses it then it appears. As for the next, prev, close button they will be icons. We also, decided to keep most elements/buttons black and white/simple cuz to many colours make it distracting.
