### ISSUE TITLE
Spacing inconsistency in overlay

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2015#25]
![screen shot 2015-03-03 at 5 04 54 pm](https://cloud.githubusercontent.com/assets/105192/6473480/9371235e-c1c7-11e4-87fd-215f817ddebc.png)

The image of the person has space above it before the edge of the overlay but the portfolio works does not. Should they match?

**Comment by mart0855** [comment]
Added margin-top to .right container
