### ISSUE TITLE
Videos not loading

### ISSUE THREAD

**Issue by birchy009** [algonquindesign-grads/2015#30]

**Comment by thomasjbradley** [comment]
In a specific browser?

**Comment by birchy009** [comment]
I'm not seeing anything in Chrome, in Firefox, they are not loading where they are meant to

**Comment by coll0335** [comment]
and the styling is really off/broken in firefox as well.

**Comment by thomasjbradley** [comment]
Firefox is looking okay to me... a little chuggy, scroll-wise.
What version are you looking in?

**Comment by birchy009** [comment]
I believe Mark fixed the issue, I was wondering though, if we could avoid the black borders?
![screen shot 2015-03-07 at 12 36 06](https://cloud.githubusercontent.com/assets/6340876/6542454/90288d5c-c4c6-11e4-99b6-ce7dac25acb4.png)

**Comment by thomasjbradley** [comment]
I've tried quite a bit to get the Vimeo embedding to work properly. But the only solution I have would be to display a thumbnail of the Vimeo videos in place, then when clicked the video pops up and plays.

I mentioned this quickly to Mark, but I think the team needs to discuss and decide on a solution.

**Comment by birchy009** [comment]
I set a height for the initial iframe and go it to look like this
![screen shot 2015-03-07 at 12 40 27](https://cloud.githubusercontent.com/assets/6340876/6542474/2f3c1a62-c4c7-11e4-9171-f6fb310b26fc.png)
But we would need multiple media queries to stop it from looking weird

**Comment by thomasjbradley** [comment]
How does that play when there's mixed images and iframes?

**Comment by birchy009** [comment]
Could be better:
![screen shot 2015-03-07 at 12 44 41](https://cloud.githubusercontent.com/assets/6340876/6542487/c1d7736c-c4c7-11e4-8e25-31d82eb3491a.png)
Is there any way we can have the images and videos be the same size? I cant figure it out

**Comment by thomasjbradley** [comment]
Our first problem was choosing an aspect ratio for the images that's incompatible with HD video. Our images are 3:2 while the videos are 16:9.

I tried using embed containers and forcing the videos into 3:2 aspect ratio, but the website blew up.
You're welcome to try:
https://github.com/algonquindesign/html-css/tree/gh-pages/modules
https://www.youtube.com/watch?v=noEcV1AFY-g&list=PLWjCJDeWfDddIWwftJxBqtHpw8CbFMXsa&index=11
