### ISSUE TITLE
Facebook preview blank

### ISSUE THREAD

**Issue by birchy009** [algonquindesign-grads/2015#32]
Is there an image we can add to amazons3 as a preview for facebook?

![screen shot 2015-03-09 at 11 03 28](https://cloud.githubusercontent.com/assets/6340876/6557526/058592b2-c64c-11e4-9ea2-3020dbc11ca7.png)

**Comment by thomasjbradley** [comment]
That's a good idea. You'll have to change this URL to point to S3 also:
https://github.com/algonquindesign-grads/2015/blob/gh-pages/index.html#L10
I suggest using a JPG instead of an SVG.

**Comment by birchy009** [comment]
Yeah I put that there as a test because I didn't have access to s3

**Comment by birchy009** [comment]
Is there any reason its showing the Coming Soon pages meta info?

**Comment by mart0855** [comment]
Tiffany mentioned that it may take time for the internet to recognize the new metadata. Not sure what she meant by that...

**Comment by thomasjbradley** [comment]
What Tiffany makes sense. I also cleared the cache for the website and hopefully that will help.
