### ISSUE TITLE
Updated teachers photo

### ISSUE THREAD

**Issue by hbrittany** [algonquindesign-grads/2015#39]
I have just switched the teachers.jpg in AmazonS3 to the new one including Chris Jones. Has not automatically updated yet.

**Comment by thomasjbradley** [comment]
It was cached in our system. I've purged the cache and it should be working now.

**Comment by thomasjbradley** [comment]
Though it's a little too compressed.

**Comment by mart0855** [comment]
Yeah, the image is really pixelated in large screens. It is the same file size as one of the portraits yet spans the whole page.

**Comment by hbrittany** [comment]
Shelley has sent me a less compressed version. I just switched them. (shelley said mark was going to swap them early but I noticed it is still very blurry on the site so I swapped for my new one  just incase he hasn't had a chance)
